### PR TITLE
Added StreamLit as example project

### PR DESCRIPTION
**Pull request by mzieniukbw**
### Description
Added new example project with StreamLit.

### Shape
The StreamLit is a web framework, that renders entire UI using python code.
For FIDO2 WebAuthn cryptographic exchanges with the browser, the Passwordless.dev JavaScript client have been used, while StreamLit renders the UI and it's components.
With this design, no custom written JS code is needed for the StreamLit UI to function correctly.

Technically the same could be achieved using https://github.com/thunderbug1/streamlit-javascript or plain html, but it's easier to have it as standalone component, since it can be easily used and it embeds the passwordless client dependency.

### Screenshots
Screenshot 2024-04-24 at 23 25 26
Screenshot 2024-04-24 at 23 25 33
Screenshot 2024-04-24 at 23 26 57

### CODE REVIEW

**Comment by antonlydell** [comment]
A nice example that allows you to both register and sign in. Looks good. See my comments above for possible improvements. 

Have you tried to sign in to the app example from another device than your development machine?
When I have tried this (running Streamlit on http://localhost:8501 and https://localhost:8501 and signing in from my phone) I have receive errors from the browser.

**Review by jonashendrickx — APPROVED** [review]

**Comment by mzieniukbw** [comment]
@antonlydell I do not see any comments, did you publish them in this PR ?
What errors do you see ?
The WebAuthn requires the browser to be running with trusted ssl cert under `https://`, but `http://localhost` is also accepted for development.
I have encountered issues outside of localhost though, with error `Invalid 'sameOriginWithAncestors' value`. From what i understand, this might be due to how streamlit handled components through and `<iframe>`, which would be an issue. I will see what i can do if this is related to that or not.

**Comment by antonlydell** [comment]
@mzieniukbw I wrote some comments to the selected parts from the "Files changed" tab. I mentioned you in the comments now. Can you see them?

Ok interesting. I have also understood that <iframe> can cause issues with WebAuthn if you do not have the correct permission policy set. I'm not an expert so any advice in this area would be helpful. I will try to deploy an example app with proper https and see If I can get it to work on mobile phones.

**Comment by mzieniukbw** [comment]
@antonlydell I have tested this outside of `localhost` and indeed it does not work, failing with error: `Invalid 'sameOriginWithAncestors' value`.

All Streamlit components are rendered within an `<iframe>`, which not only does not contain the necessary access policies for the WebAuthn, but also the iframe `src` does not exactly match, since it contains the additional path. The framework does not allow for any customization, so dead end.
The `st.html("<script>...</script>")` does not work, because the input is sanitized (it renders in html as nothing).
The `st.write("<script>...</script>",unsafe_allow_html=True)` does not work either, since the script is not within the `<body>` tag directly, but far within various html elements, so Chromium based browsers won't load the script.
So it does not seem like there is any way to inject any JS code into the html officially.

The only other two options that might work are:
1. inject JS by modifying index.html within the Streamlit on runtime https://github.com/TangleSpace/hydralit_components/blob/main/hydralit_components/Experimental/experiments.py
This might break any time, but it's easier to deploy when it's just a dependency.
2. inject JS with an http proxy before the html is sent to the browser, example with Nginx: https://stackoverflow.com/questions/19700871/how-to-inject-custom-content-via-nginx
I would recommend this, since this will always work.

I will explore both options and update the Streamlit example with either one.

**Comment by antonlydell** [comment]
@mzieniukbw : Thank you for testing this out and digging in to a possible solution. I really appreciate it!

How did you deploy your Streamlit app? Did you set your Streamlit-app to run in https mode behind a reverse proxy?
E.g.

```toml
# .streamlit/config.toml

[server]
sslCertFile = '/path/to/certchain.pem'
sslKeyFile = '/path/to/private.key'
```
See [Streamlit https mode](https://docs.streamlit.io/develop/concepts/configuration/https-support)

I have deployed an example app at Streamlit Community Cloud to test my own package [streamlit-passwordless](https://github.com/antonlydell/streamlit-passwordless) and I can register and sign in ok on all my tested devices except for iPhone. I am working on a fix for the iPhone issue. I do not know Streamlit's depolyment process on Streamlit Community.

See : 
- https://passwordless.streamlit.app/
- [Phone : Client error "The document is not focused" #5](https://github.com/antonlydell/streamlit-passwordless/issues/5)

**Comment by mzieniukbw** [comment]
@antonlydell I did test with self-signed certificates (but trusted in OS) as well as reverse proxy with valid cert on public domain.

I was able to make it working, see https://github.com/bitwarden/passwordless-python/pull/44/commits/741f1648aca1246b41095b56b62300e2ea33fe66 commit.
The change requires the Passwordless Client JS lib to be loaded through root html and not within the iframe. It does not require nginx or any external dependency - see change in `examples/streamlit/passwordless_auth/frontend/src/main.js`
Also i have updated the README.md file with the steps required to make it production ready.

Onto, why does the Passwordless Client does not work when it's loaded within the iframe ? At the moment don't know, but we are investigating whether there is anything to improve in the client library.

**Review by jonashendrickx — APPROVED** [review]

**Review by jonashendrickx — APPROVED** [review]

**Comment by antonlydell** [comment]
Nice work @mzieniukbw !

**Pull request merged**
